CMakeLists.txt

Accept option `-DPYTHON_EXECUTABLE=/path/to/python3` for cmake configuration.
For VS Code integration, for example, set:
```json
{
"cmake.configureSettings": {
"PYTHON_EXECUTABLE:FILEPATH": "/home/PanXuehai/Miniconda3/envs/metaopt/bin/python3"
}
}
```
in `.vscode/settings.json`.

feat(CMakeLists.txt): custom Python executable path

---

.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/tests.yml
CMakeLists.txt
conda-recipe.yaml
requirements.txt
setup.py
tests/requirements.txt

Update dependency PyTorch to 1.12 due to packaging issue for `functorch`. See `functorch`'s release note: https://github.com/pytorch/functorch/releases/tag/v0.2.0 and issue pytorch/pytorch#80489.
Command:
```bash
CONDA_OVERRIDE_CUDA=11.7 conda env create --file conda-recipe.yaml
conda activate torchopt
pip3 install -e .
```
while create a dev environment with CUDA Toolkit 11.6.0, PyTorch (CUDA) 1.12.0, functorch 0.2, and JAX (CUDA) 0.3.14.
Stdout:
```console
$ CONDA_OVERRIDE_CUDA=11.7 conda env create -f conda-recipe.yaml
Collecting package metadata (repodata.json): done
Solving environment: done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Collecting package metadata (repodata.json): done
Solving environment: done
Preparing transaction: done …
```

deps: bump PyTorch version to 1.12

---

CHANGELOG.md
src/adam_op/adam_op_impl.cpp

use dynamic process number instead of the fixed number 32

feat(custom_op): use dynamic process number

---

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/tests.yml
.readthedocs.yaml
CHANGELOG.md
CMakeLists.txt
README.md
docs/source/developer/contributing.rst
docs/source/spelling_wordlist.txt
pyproject.toml
tests/requirements.txt

Use [`cibuildwheel`](https://github.com/pypa/cibuildwheel) to build `manylinux` wheels in GitHub Actions and update the contribution guide.

feat(workflows): cibuildwheel integration

---

.github/workflows/lint.yml
.github/workflows/tests.yml
CHANGELOG.md
conda-recipe.yaml
include/adam_op/adam_op.h
include/adam_op/adam_op_impl_cpu.h
include/adam_op/adam_op_impl_cuda.cuh
include/common.h
pyproject.toml
src/adam_op/adam_op.cpp
src/adam_op/adam_op_impl_cpu.cpp
src/adam_op/adam_op_impl_cuda.cu
tests/requirements.txt

Use `double` for Python type `float` and `int64_t` for Python type `int`.

chore(accelerated_op): use correct Python Ctype for pybind11 function prototype

---

CHANGELOG.md
CMakeLists.txt
src/adam_op/adam_op.cpp

Fix CUDA build by manually adding a new macro `__CUDA_ENABLED__`. Macro `__CUDACC__` is not always defined by `nvcc`. See:
https://github.com/pytorch/pytorch/blob/4d3f7df33fa49a80b20ae328d5a5d71c655e3634/cmake/Modules_CUDA_fix/upstream/FindCUDA/run_nvcc.cmake#L190-L194

fix(CMakeLists.txt): fix CUDA build for accelerated OP

---

.gitignore
CHANGELOG.md
torchopt/_src/alias.py
torchopt/_src/clip.py
torchopt/_src/hook.py
torchopt/_src/optimizer/adam.py
torchopt/_src/optimizer/base.py
torchopt/_src/optimizer/meta/adam.py
torchopt/_src/optimizer/meta/base.py
torchopt/_src/optimizer/meta/rmsprop.py
torchopt/_src/optimizer/meta/sgd.py
torchopt/_src/optimizer/rmsprop.py
torchopt/_src/schedule.py
torchopt/_src/transform.py
torchopt/_src/update.py
torchopt/_src/utils.py
torchopt/_src/visual.py

fix(transform): fix momentum trace

---

CHANGELOG.md
tests/test_schedule.py
torchopt/_src/alias.py
torchopt/_src/implicit_diff.py
torchopt/_src/linalg.py
torchopt/_src/schedule.py
torchopt/_src/transform.py
torchopt/_src/utils.py

fix: fix lr scheduling

---

.gitignore
CHANGELOG.md
Makefile
README.md
docs/requirements.txt
docs/source/api/api.rst
docs/source/index.rst
docs/source/spelling_wordlist.txt
docs/source/torchopt101/torchopt-101.rst
tests/test_implicit.py
torchopt/_src/implicit_diff.py
torchopt/_src/linalg.py
torchopt/_src/linear_solve.py
tutorials/5_Implicit_Differentiation.ipynb

docs(implicit_diff): implicit differentiation integration

---

.pylintrc
CHANGELOG.md
Makefile
docs/source/api/api.rst
docs/source/spelling_wordlist.txt
tests/test_implicit.py
torchopt/linalg/__init__.py
torchopt/linalg/cg.py
torchopt/linalg/ns.py
torchopt/linalg/utils.py
torchopt/linear_solve/__init__.py
torchopt/linear_solve/cg.py
torchopt/linear_solve/inv.py
torchopt/linear_solve/normal_cg.py
torchopt/linear_solve/utils.py
torchopt/pytree.py

matrix inversion linear solver with neumann series approximation

feat(linear_solve): matrix inversion linear solver with neumann series approximation

---

.github/workflows/set_release.py
CHANGELOG.md
docs/source/api/api.rst
docs/source/spelling_wordlist.txt
torchopt/__init__.py
torchopt/hook.py
torchopt/transform/__init__.py
torchopt/transform/nan_to_num.py

feat(hook): add `nan_to_num` hooks

---

torchopt/base.py
torchopt/optim/base.py
torchopt/optim/func/base.py
torchopt/optim/meta/base.py
torchopt/transform/scale_by_adam.py
torchopt/utils.py

Fixes #116
Moving module to another device after defining the meta-optimizer:
```python
module = ...
torchopt.MetaAdam(module)
module = module.cuda()
```
The optimizer `state` will be lazily initialized on the first `step` call.

feat: add lazy-init for the optimizer states

---

.github/workflows/tests.yml
CHANGELOG.md
pyproject.toml
tests/requirements.txt
tests/test_implicit.py

test(workflows): enable tests on Windows

---

CHANGELOG.md
codecov.yml
tests/.coveragerc
tests/test_alias.py
tests/test_implicit.py
tests/test_nn.py
tests/test_zero_order.py
torchopt/base.py
torchopt/diff/implicit/nn/module.py
torchopt/diff/zero_order/nn/module.py
torchopt/transform/scale_by_adam.py
torchopt/typing.py
torchopt/utils.py

fix: fix transpose empty iterable with `zip(*nested)` in transformations

---

torchopt/utils.py

Added detach_buffers keyword arg to the nn.Module version of extract_state_dict and removed with_buffers from the MetaOptimizer version of extract_state_dict.
Fixes #161
Comment: there currently are no tests for type checking, so there weren't any tests that needed updating.

Fix overloading of extract_state_dict

---

.github/workflows/lint.yml
.pre-commit-config.yaml
CHANGELOG.md
CMakeLists.txt
conda-recipe.yaml
docs/conda-recipe.yaml
docs/requirements.txt
torchopt/alias/sgd.py
torchopt/alias/utils.py
torchopt/distributed/api.py
torchopt/linalg/cg.py
torchopt/linalg/ns.py
torchopt/nn/stateless.py
torchopt/transform/add_decayed_weights.py
torchopt/transform/scale_by_adadelta.py
torchopt/transform/scale_by_adam.py
torchopt/transform/scale_by_adamax.py
torchopt/transform/scale_by_rms.py
torchopt/transform/scale_by_rss.py
torchopt/transform/scale_by_schedule.py
torchopt/transform/scale_by_stddev.py
torchopt/transform/trace.py
torchopt/transform/utils.py
torchopt/utils.py

Fix `None` handling for optimizers.

fix: fix `optree` compatibility for multi-tree-map with `None` values

---

README.md
docs/source/index.rst

docs: update citation references

---

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/tests.yml
.pre-commit-config.yaml
CHANGELOG.md
CMakeLists.txt
Dockerfile
Makefile
README.md
conda-recipe-minimal-cpu.yaml
conda-recipe-minimal.yaml
conda-recipe.yaml
docs/conda-recipe.yaml
docs/requirements.txt
docs/source/developer/contributing.rst
docs/source/index.rst
examples/requirements.txt
pyproject.toml
requirements.txt
tests/helpers.py
tests/requirements.txt
tutorials/requirements.txt

deps(torch): support PyTorch 2.0+ only

---

CHANGELOG.md
setup.py

refactor(setup.py): refactor build system

---

.github/workflows/build.yml
CHANGELOG.md
Makefile
pyproject.toml

feat(workflows): enable Python 3.12 build
