CMakeLists.txt
setup.py

Fix build for the C extension.

fix(CMakeLists.txt): fix building from source

---

.github/ISSUE_TEMPLATE/questions_help_support.md

Add another issue template for question/help/support.

feat: add question/help/support issue template

---

CHANGELOG.md
CITATION.cff
README.md
conda-recipe.yaml
docs/conda-recipe.yaml
docs/requirements.txt
docs/source/developer/contributing.rst
examples/requirements.txt
pyproject.toml
requirements.txt
tests/requirements.txt
torchopt/version.py
tutorials/requirements.txt

Fix upstream wheel issues of PyTorch and FuncTorch by bumping versions.
See https://github.com/pytorch/pytorch/releases/tag/v1.12.1 and https://github.com/pytorch/functorch/releases/tag/v0.2.1.

ver: bump version to 0.4.3

---

CHANGELOG.md
README.md

- Update image link to support pypi image rendering.
- Update future plan to track the finished and unfinished

fix(README): update image link and future plan

---

.github/PULL_REQUEST_TEMPLATE.md
torchopt/_src/transform.py

Fix lint and refine pull request template

fix: pass lint

---

.github/workflows/tests.yml
Makefile

Upload code coverage report, a reminder of improving test coverage and new feature test. #29 

feat: upload code coverage report

---

README.md
conda-recipe.yaml
docs/conda-recipe.yaml
docs/requirements.txt
docs/source/examples/MAML.rst
docs/source/index.rst

- Update installation in README and docs
- Update docutils dependency for rendering

fix: update installation

---

CHANGELOG.md
tests/high_level/test_high_level_inplace.py
tests/low_level/test_low_level.py
tests/test_clip.py
torchopt/_src/alias.py
torchopt/_src/optimizer/adam.py
torchopt/_src/optimizer/meta/adam.py
torchopt/_src/optimizer/meta/rmsprop.py
torchopt/_src/optimizer/meta/sgd.py
torchopt/_src/optimizer/rmsprop.py
torchopt/_src/optimizer/sgd.py

Add new option `maximize` to optimizers

feat: add option `maximize` to optimizers

---

.github/workflows/build.yml
CHANGELOG.md
torchopt/_src/transform.py
torchopt/version.py

fix: change counts to scalar tensors

---

Makefile
docs/source/spelling_wordlist.txt
pyproject.toml
tests/requirements.txt
torchopt/linalg.py
torchopt/linear_solve.py

fix doc8 version error https://github.com/PyCQA/doc8/issues/112

fix: appease linters

---

torchopt/implicit_diff.py
torchopt/linear_solve.py

support the situation that matrix A is symmetric definite positive (sdp)

feat(implicit): add option for matrix is sdp

---

conda-recipe.yaml
torchopt/clip.py

fix(clip): fix `clip_grad_norm` for empty tensor trees

---

README.md
conda-recipe-minimal.yaml
conda-recipe.yaml
docs/conda-recipe.yaml
pyproject.toml
requirements.txt
torchopt/hook.py
torchopt/optim/base.py
torchopt/pytree.py
torchopt/transform/utils.py
torchopt/typing.py
torchopt/utils.py

deps: bump optree to 0.4.0

---

torchopt/nn/stateless.py

Cache intermediate submodules for better performance.
Before:
```python
In [1]: import torchopt
In [2]: from torchvision.models import resnet152
In [3]: model = resnet152()
In [4]: params = dict(model.named_parameters())
In [5]: %timeit torchopt.nn.swap_state(model, params)
1.16 ms ± 6.23 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```
After:
```python
In [1]: import torchopt
In [2]: from torchvision.models import resnet152
In [3]: model = resnet152()
In [4]: params = dict(model.named_parameters())
In [5]: %timeit torchopt.nn.swap_state(model, params)
677 µs ± …
```

perf(nn/stateless): cache intermediate submodules

---

.editorconfig
.pre-commit-config.yaml
docs/source/bibtex.json

feat(pre-commit): add `clang-format` hook

---

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/tests.yml
CHANGELOG.md

The GitHub Action seems out of maintenance.

refactor(workflows): rewrite setup CUDA Toolkit logic

---

Dockerfile
Makefile

fix(Dockerfile): fix missing versioned packages

---

.flake8
.pre-commit-config.yaml
Makefile
conda-recipe.yaml
pyproject.toml
setup.py
tests/requirements.txt
torchopt/_C/adam_op.pyi
torchopt/diff/implicit/decorator.py
torchopt/diff/zero_order/decorator.py
torchopt/diff/zero_order/nn/module.py
torchopt/distributed/__init__.py
torchopt/distributed/autograd.py
torchopt/linalg/ns.py
torchopt/typing.py

feat: add flake8 plugins and enable pre-commit hook

---

conda-recipe.yaml
pyproject.toml
torchopt/optim/base.py
torchopt/utils.py

- pytorch/pytorch#96804
- pytorch/pytorch#94937

fix: fix CI failure for PyTorch 2.0

---

conda-recipe-minimal-cpu.yaml
setup.py

feat: add conda recipe for CPU-only machine

---

torchopt/diff/implicit/decorator.py

Update license header in torchopt.implicit_diff

docs(diff/implicit): update license header

---

docs/source/explicit_diff/explicit_diff.rst

docs: fix typo in explicit differentiation
